"""Configuration objects and shared constants.

Everything that used to be a module-level global or a hard-coded literal in the
original single-file script lives here, so that a run can be reproduced from a
config file / environment variables alone. No credentials or host names are
committed to this repository; see ``.env.example``.
"""

from __future__ import annotations

import os
from dataclasses import dataclass, field
from typing import Dict, List, Optional, Tuple

# --------------------------------------------------------------------------- #
# Benchmark definition
# --------------------------------------------------------------------------- #

#: Target score and optimisation direction for every benchmark task.
#: The target is the medal-threshold / reference score used to decide whether a
#: task counts as "solved"; the direction says whether higher or lower is better.
COMPETITION_TARGETS: Dict[str, Tuple[float, str]] = {
    "tensorflow-speech-recognition-challenge": (0.32, "maximize"),
    "nomad2018-predict-transparent-conductors": (0.0715, "minimize"),
    "plant-pathology-2020-fgvc7": (0.9405, "maximize"),
    "jigsaw-toxic-comment-classification-challenge": (0.9762, "maximize"),
    "whale-categorization-playground": (0.3279, "maximize"),
    "stanford-covid-vaccine": (0.48, "minimize"),
    "text-normalization-challenge-english-language": (0.98, "maximize"),
    "tabular-playground-series-dec-2021": (0.9493, "maximize"),
    "tabular-playground-series-may-2022": (0.8938, "maximize"),
    "playground-series-s5e6": (0.3319, "maximize"),
    "new-york-city-taxi-fare-prediction": (4.8677, "minimize"),
    "ventilator-pressure-prediction": (2.8233, "minimize"),
    "cmi-detect-behavior-with-sensor-data": (0.80, "maximize"),
    "um-game-playing-strength-of-mcts-variants": (0.30, "minimize"),
    "clinic-data": (0.86, "maximize"),
    "demo-shopee-iet-competition": (0.988, "maximize"),
    "house-prices-advanced-regression-techniques": (0.0001, "minimize"),
}

DEFAULT_DIRECTION = "maximize"

#: Relative directory the generated solution is told to read its data from.
DATA_ROOT_TEMPLATE = "../input/{competition}/"

#: File the generated solution must produce.
SUBMISSION_FILENAME = "submission.csv"

# --------------------------------------------------------------------------- #
# Inference budgets (Algorithm 1)
# --------------------------------------------------------------------------- #

#: N_meta -- the number of outer meta-steps for one task. Each meta-step issues
#: at most one policy-model call, so this is also the worst-case number of
#: reasoning calls per task.
N_META = 10

#: N_repair -- the number of LocalRepair attempts allowed inside a single
#: meta-step. Algorithm 1 runs the inner loop for k = 0..N_repair, i.e. one
#: initial execution plus at most N_repair repairs, so a meta-step performs at
#: most N_repair + 1 executions.
N_REPAIR = 5

#: tau_sim -- semantic-deadlock threshold. The current error log is compared
#: against every previous error log in the history; if the maximum cosine
#: similarity exceeds this value, the trajectory is declared deadlocked and
#: control returns to SATE instead of attempting another local repair.
TAU_SIM = 0.8

#: Sentence encoder used for the deadlock check.
SIMILARITY_MODEL_NAME = "paraphrase-multilingual-MiniLM-L12-v2"

#: Number of timeouts within one meta-step after which the refinement loop
#: abandons the current candidate. This is a harness-level guard rather than a
#: quantity named in Algorithm 1.
MAX_CONSECUTIVE_TIMEOUTS = 2

# --------------------------------------------------------------------------- #
# Execution sandbox
# --------------------------------------------------------------------------- #

#: Machine-readable prefix the runner puts on every timeout message. Timeout
#: detection keys on this prefix rather than on free-text phrases.
TIMEOUT_SENTINEL = "TIMEOUT_ERROR:"

#: A pre-existing submission.csv counts as "regenerated by this run" only if its
#: mtime moved by more than this many seconds.
SUBMISSION_MTIME_TOLERANCE_SEC = 1.0

DEFAULT_CPU_LIMIT = 4
DEFAULT_DL_TESTING_TIMEOUT = 1800  # seconds, smoke test with epochs=1
DEFAULT_NORMAL_TIMEOUT = 7200      # seconds, ordinary / full training run

#: Safety margin applied when extrapolating the full-training timeout from the
#: measured single-epoch runtime.
FULL_TRAINING_TIMEOUT_MARGIN = 1.2

#: Seconds to wait after a leaderboard submission before polling for the score.
SUBMISSION_POLL_DELAY_SEC = 120

# --------------------------------------------------------------------------- #
# Sampling-parameter search space
# --------------------------------------------------------------------------- #

TEMPERATURE_HARD_MIN = 0.3
TEMPERATURE_HARD_MAX = 1.2
TOP_P_HARD_MIN = 0.8
TOP_P_HARD_MAX = 0.98

#: How far the per-episode search window may extend around the starting point.
TEMPERATURE_WINDOW_DOWN = 0.3
TEMPERATURE_WINDOW_UP = 0.4
TOP_P_WINDOW_DOWN = 0.1
TOP_P_WINDOW_UP = 0.08

#: When a previous episode's best parameters are reused, they are nudged
#: slightly downwards so that the new episode can explore upwards again.
HISTORICAL_TEMPERATURE_BACKOFF = 0.02
HISTORICAL_TOP_P_BACKOFF = 0.005

#: Recovery heuristic: if an episode produced no scored submission at all, the
#: lowest-temperature execution failure is recorded with these bonuses added.
RECOVERY_TEMPERATURE_BONUS = 0.04
RECOVERY_TOP_P_BONUS = 0.01

#: Starting (temperature, top_p) per task family, before per-node offsets.
PROBLEM_TYPE_BASE_CONFIGS: Dict[str, Tuple[float, float]] = {
    "nlp_tasks": (0.8, 0.92),
    "vision_tasks": (0.7, 0.90),
    "tabular_data": (0.6, 0.88),
    "time_series": (0.75, 0.91),
    "default": (0.7, 0.90),
}

#: Per-unit offsets applied when several nodes explore the same task in
#: parallel with different ``config_adjustment`` values.
CONFIG_ADJUSTMENT_TEMPERATURE_STEP = 0.08
CONFIG_ADJUSTMENT_TOP_P_STEP = 0.02

#: Keyword rules used to guess the task family from its name and prompt.
PROBLEM_TYPE_KEYWORDS: Dict[str, List[str]] = {
    "nlp_tasks": ["text", "language", "nlp", "sentiment", "translation", "normalization"],
    "vision_tasks": ["image", "vision", "cnn", "computer-vision", "photo", "picture", "pathology"],
    "time_series": ["time-series", "forecast", "temporal", "sequence", "trend"],
}

# --------------------------------------------------------------------------- #
# Code extraction: non-English response handling
# --------------------------------------------------------------------------- #

#: The code extractor separates program lines from prose lines by keyword. The
#: policy models evaluated here sometimes answer in Chinese even when prompted in
#: English, so the extractor also carries a CJK marker list. Set this to False to
#: run the extractor on English markers alone; extraction quality on non-English
#: responses degrades accordingly.
INCLUDE_CJK_EXTRACTION_MARKERS = True

#: Phrases that mark a line as prose rather than code, in Chinese.
CJK_PROSE_MARKERS: Tuple[str, ...] = (
    "說明", "解釋", "注意", "這個", "以上", "總結", "步驟", "方案",
    "但需要驗證", "例如", "假設", "因此", "等等", "接下來", "然後",
    "本方案", "改進", "優化", "性能", "指標", "關鍵點", "匹配", "轉換", "合併",
)

#: Headings a Chinese-language response tends to put before its final program.
CJK_SOLUTION_HEADING_PATTERNS: Tuple[str, ...] = (
    r"###?\s*完整改進方案\s*$",
    r"###?\s*具體實施步驟\s*$",
    r"##?\s*完整實現代碼\s*$",
    r"###?\s*完整實現方案\s*$",
    r"###?\s*完整解決方案\s*$",
    r"##?\s*完整代碼實現\s*$",
    r"###?\s*完整改進代碼\s*$",
    r"###?\s*完整程式碼\s*$",
    r"###?\s*代碼實現\s*$",
    r"###?\s*程式實現\s*$",
    r"###?\s*最終實現\s*$",
    r"###?\s*實現方案\s*$",
)

# --------------------------------------------------------------------------- #
# Prompt set
# --------------------------------------------------------------------------- #

#: Which prompt set the pipeline uses. ``"zh"`` is the wording that produced the
#: reported results and is therefore the default; ``"en"`` is a translation kept
#: for readability and is a different experiment. Override with the
#: ``AUTODS_PROMPT_LANGUAGE`` environment variable or ``--prompt-language``.
PROMPT_LANGUAGE = os.environ.get("AUTODS_PROMPT_LANGUAGE", "zh")

# --------------------------------------------------------------------------- #
# Persistence
# --------------------------------------------------------------------------- #

BEST_HISTORICAL_PARAMS_FILE = "best_historical_parameters.json"


# --------------------------------------------------------------------------- #
# Dataclasses
# --------------------------------------------------------------------------- #

@dataclass
class GeneratorConfig:
    """The policy model under evaluation, served behind an OpenAI-compatible API.

    ``api_key`` is unused by most local servers but is required by the client
    library, hence the placeholder default.
    """

    base_url: str
    model: str
    api_key: str = "EMPTY"
    max_tokens: int = 4096

    @classmethod
    def from_env(cls) -> "GeneratorConfig":
        return cls(
            base_url=os.environ.get("GENERATOR_API_BASE", "http://localhost:8000/v1"),
            model=os.environ.get("GENERATOR_MODEL", "local-policy-model"),
            api_key=os.environ.get("GENERATOR_API_KEY", "EMPTY"),
        )


@dataclass
class CorrectorConfig:
    """The frozen auxiliary model used for error repair and error summarisation.

    It is deliberately a different model from the generator: the generator is
    the subject of the experiment, the corrector is part of the fixed harness.
    """

    api_url: str
    model: str
    api_key: str = ""
    correction_max_tokens: int = 8192
    correction_temperature: float = 0.1
    analysis_max_tokens: int = 4096
    analysis_temperature: float = 0.3
    referer: str = "https://localhost"
    title: str = "AutoDS-Solver code corrector"

    @classmethod
    def from_env(cls) -> "CorrectorConfig":
        return cls(
            api_url=os.environ.get(
                "CORRECTOR_API_URL", "https://openrouter.ai/api/v1/chat/completions"
            ),
            model=os.environ.get("CORRECTOR_MODEL", ""),
            api_key=os.environ.get("CORRECTOR_API_KEY", ""),
        )


@dataclass
class ExecutionConfig:
    """Resource limits applied to every generated program."""

    cpu_limit: int = DEFAULT_CPU_LIMIT
    dl_testing_timeout: int = DEFAULT_DL_TESTING_TIMEOUT
    normal_timeout: int = DEFAULT_NORMAL_TIMEOUT
    pin_cpu_affinity: bool = True


@dataclass
class ExperimentConfig:
    """One full experiment: a set of tasks run for a number of episodes."""

    competitions: List[str]
    prompts_path: str
    generator: GeneratorConfig
    corrector: CorrectorConfig
    execution: ExecutionConfig = field(default_factory=ExecutionConfig)
    n_meta: int = N_META
    n_repair: int = N_REPAIR
    max_episodes: int = 1
    node_id: str = "node-0"
    config_adjustment: int = 0
    cuda_device: Optional[str] = None
    initial_temperature: Optional[float] = None
    initial_top_p: Optional[float] = None
    output_root: str = "."
    submit_to_leaderboard: bool = True
    history_file: str = BEST_HISTORICAL_PARAMS_FILE
